### PR TITLE
[dnm] add dvid remote (incomplete implementation)

### PR DESCRIPTION
**Pull request by j6k4m8**

### CODE REVIEW

**Comment by kunallillaney** [comment]
@j6k4m8 Should we close this request since there has been nothing new on this for 8 months

**Review by Aeusman — COMMENTED** [review]
@j6k4m8 Did this ever get completed?

**Comment by kunallillaney** [comment]
@Aeusman this is low priority.

**Comment by Aeusman** [comment]
@kunallillaney Agreed, this was more of a question of whether the PR still needs to remain open

**Pull request closed without merging**
