### PR TITLE
Changing from PIL to tiffile

### PR DESCRIPTION
**Pull request by Aeusman**
This proposed change will move convert/tiff from PIL reliance to tifffile, which appears to be more useful/less prone to cause problems during conversion.

### CODE REVIEW

**Comment by Aeusman** [comment]
@j6k4m8 and @wrgr - For your review

**Comment by Aeusman** [comment]
Fix for #205 and probably #192 since tests now pass properly. @j6k4m8 @wrgr - for review

**Comment by j6k4m8** [comment]
Huge (YUGE!!) fan of this. Really excited to see this, let's get it merged!

**Comment by Aeusman** [comment]
(Yay reducing the issue page to fit on one page!) - I'm happy to merge this in, but I think @wrgr will want to look at it first.

**Comment by wrgr** [comment]
I did want to and did look.  Thanks!!

**Pull request merged**
